### PR TITLE
Remove Burner Wallet

### PR DESCRIPTION
**Pull request by naz3eh**
This PR fixes issue #28 by removing the Burner Wallet.

### CODE REVIEW

**Comment by Nazeeh21** [comment]
@Cali93 Please review this PR and let me know if any of the changes are required.

**Review by codenamejason — COMMENTED** [review]
If you are trying to remove the burner wallet this is not the right way. You are just removing the qr reader.

**Comment by codenamejason** [comment]
Screen Shot 2021-11-11 at 9 06 01 AM

this is the code you need to edit in Account.jsx

**Comment by Nazeeh21** [comment]
Okay, thanks for helping me. I'll soon make the changes

**Comment by Nazeeh21** [comment]
> Screen Shot 2021-11-11 at 9 06 01 AM
> 
> this is the code you need to edit in Account.jsx

@codenamejason I am not able to find the code you pointed. 
image

Am I searching in the wrong file? Also, I tried searching globally for **burner** in the entire codebase and I didn't find any.

**Comment by Cali93** [comment]
Closed by https://github.com/moonshotcollective/drecruit/pull/61

**Comment by Cali93** [comment]
Closed by https://github.com/moonshotcollective/drecruit/pull/61

**Comment by codenamejason** [comment]
I can do this if you want @Cali93

**Comment by Cali93** [comment]
> I can do this if you want @Cali93

That's cool it has been removed by @Dhaiwat10 in an other PR.

**Pull request closed without merging**
