### PR TITLE
Revert "Use local provider to get dev profiles"

### PR DESCRIPTION
**Pull request by QEDK**
Reverts moonshotcollective/drecruit#90

This breaks the network detection and network switch behaviour. A PR to address this should also incorporate the external logic.

### CODE REVIEW

**Comment by QEDK** [comment]
Cc @damianmarti @Cali93

**Comment by damianmarti** [comment]
@QEDK can you please explain what do you think that needs to be done here to allow to see the profiles when no wallet is connected?

**Comment by QEDK** [comment]
@damianmarti The complicated way would involve setting a state when `injectedProvider` is set and when attempting to do a tx with a local provider, we detect the state to ask them to connect their wallet if needed. It's important to understand that `localProvider` is only a provider and never a signer, hence all attempts to do a tx will error in the frontend.

The easy way is the current behaviour of requiring you to connect your wallet.

Now, since we can effectively detect networks when connecting with the injected provider, we can move the network switch mechanism to that level, but it needs to be a solution that does not introduce regressions.

Cc @Cali93 just to cross-check and correct me or suggest necessary improvements

**Comment by damianmarti** [comment]
@QEDK I understand, but just for the read operations like getting the dev profiles I think that we can use the localProvider and if the user wants to interact (like request the private profile from a dev) the app will show a message that the user needs to connect your wallet first.

**Comment by QEDK** [comment]
@damianmarti Exactly, and that's something to incorporate with state I believe (or whatever is optimal). The issue is that the user should not be using the local provider for transactions and having the interactions fail.

**Comment by damianmarti** [comment]
@QEDK yes! But I just changed the provider to get the dev profiles. Nothing will break with this change or maybe I'm missing something...

**Comment by damianmarti** [comment]
@QEDK I see the error when trying to **Request contact information**....

**Comment by QEDK** [comment]
> @QEDK yes! But I just changed the provider to get the dev profiles. Nothing will break with this change or maybe I'm missing something...

It also breaks the network switching behaviour because we rely on `context.injectedProvider` erroring (`localProvider` always uses the correct network). For e.g.
* Have any other network other than Mumbai testnet selected in your wallet
* Click connect
The network alert dialog to add/switch network will not show up.

**Comment by damianmarti** [comment]
@QEDK thanks for all the explanation! I think we should find a easy way to use the localProvider for read operations and the injectedProvider for write operations and that everythink work well (like we did with the readContracts and writeContracts on scaffold-eth, using the localProvider for the first one and the userSigner for the last one). In this way, we can show up the public data with no connect wallet required. I will re-open the issue and look into it.

**Pull request merged**
